import { pickOwnership, seatForTeamIndex, UNRANKED_ADP_PADDING } from "../../core/draft";
import { LruMemoStore, recommendMemoized } from "../../core/draft-memo";
import { solveLineup } from "../../core/optimizer";
import type {
  ChampionshipRecommendation,
  DraftPolicyState,
  DraftTeam,
} from "../../core/draft-policy";
import type { PlayerRisk } from "../../core/roster-utility";
import type { LeagueConfig } from "../../core/season-sim";
import { perGameRate } from "./value";

/**
 * A deterministic mock draft: nine opponents drafting strictly by market rank, our seat
 * taking the recommendation panel's #1 every turn.
 *
 * This is the harness behind the #88/#89 audit, codified. The audit was a browser run on
 * production — opponents took the top of the pool sorted by ADP, our seat took the leader
 * as presented, and the roster that fell out started three players the market had never
 * ranked, benched a kicker drafted in round 9 behind another drafted in round 12, and
 * finished a half-PPR 2-FLEX draft with two wide receivers. Every one of those is a
 * property this module asserts, as a **documented expectation per check** in
 * `CHECK_DEFINITIONS`. The contract: an expectation flips only in the commit that
 * changes the measured behavior, and the flip names its mechanism — and were a commit to
 * *cause* a failure it could not fix, the honest flip is to "fail" with the PR that owns
 * the fix named, not silence. What the contract rules out is a drive-by flip: an
 * expectation edited to green without the behavior change and its cause on record in the
 * same commit. See #91 for the sequence, #64 for why the harness is policy-level.
 *
 * Since PR 2 (byes from the schedule) the harness replays in two modes, each with its own
 * expectation column: the frozen fixture verbatim, and `--schedule-byes` — the same rows
 * with byes resolved from the schedule the way ingest now resolves them
 * (`applyTeamByes`). The pair brackets the bye fix: the frozen mode measures the engine on
 * the audit's data (403 null byes, now each charged as an assumed absent week), the
 * schedule-byes mode measures it on the same board with only the byes a rebuilt board
 * would carry — every other column stays at the frozen build's values.
 *
 * Since PR 3 the engine under test carries the market-discipline gate
 * (`applyMarketGate`, `lib/core/draft-policy.ts`): through round `MARKET_GATE_ROUNDS`
 * the panel does not offer a player the board prices at `adp: null`, which is what
 * closed check (a) on the merged engine after two individually-green orderings had
 * failed it — see the check's own definition for the history.
 *
 * ## Where the replay and the audit's transcript agree, and where they cannot
 *
 * On the frozen board, the engine as PR 1 shipped it reproduced the audit's picks
 * 1.05 through 5.05 exactly — including the 2.06 capture verbatim: Gainwell leading at
 * 14.5%±1.4 with Barkley displayed at 16.2%±1.5. The fixture's `computedAt` is the build
 * #88 cites (07:01 US Eastern, which #88 rounds to "07:00"), and reproducing the
 * *displayed percentages* was strong evidence the board matches — a different board would
 * move them. Later PRs change the picks deliberately — the scoreboard is the contract,
 * not the pick list, and the audit-parity claim belongs to PR 1's commit, `b27faf6`.
 * Both PR 2 (charging null byes) and PR 4 (ranking by the paired vs-leader comparison)
 * measurably move 2.06 to Barkley on their own: Gainwell's lead needed the missing-bye
 * subsidy *and* the tie reorder at once. One discrepancy is on record rather than
 * resolved: #89.E reports Kyle Pitts absent from the market's list, while this board
 * carries him at ADP 81.7 with a bye; both cannot be literally true of the same build,
 * and the reproduced figures argue the board is right and #89.E's raw-list check missed
 * him.
 *
 * The browser transcript and a replay also cannot agree pick-for-pick in the tail: the
 * live panel recomputes after every recorded pick, the audit's automation clicked
 * whatever was *presented*, and #88 records the reply gate preventing three stale takes —
 * clicks on a player already drafted, which is only possible if the presented panel
 * lagged the recorded picks. A replay cannot and should not reproduce click timing: #91
 * defines the harness as "same board → same draft", which is this function, not the
 * browser session. The audit's unfixed findings still reproduce here through their own
 * mechanisms — see each check's definition for what the current engine measures.
 *
 * ## Why the opponents are strict-ADP
 *
 * #64 rules out grading the policy against opponents generated by the policy itself —
 * that is circular. The market's consensus draft order is the one opponent model whose
 * provenance is independent of this codebase, and "the pool sorted by ADP, top row taken"
 * is exactly what the audit's automation clicked. Players the market has not ranked sort
 * behind every player it has (`adp: null` → after every number), mirroring the pool's
 * ADP sort on `/draft`.
 *
 * ## Why the replay mirrors the page rather than calling the policy directly
 *
 * Our picks go through `recommendMemoized` — the same entry point
 * `recommend.worker.ts` uses, canonicalization included — with the page's own seed and
 * state construction (`app/(app)/draft/page.tsx`): rosters keyed off the pick-ownership
 * map with team 0 as our seat, `remainingPicks` filtered from the current pick, the pool
 * in board order. A harness that rebuilt the state its own way would measure its own
 * reconstruction, not the product; this one reproduces the audit's picks on the audit's
 * board build, which is what makes its failures evidence rather than anecdote.
 *
 * Pure by construction: the board arrives as data (the frozen fixture under
 * `tests/fixtures/`), the engine is seeded, and the same inputs replay the same 160
 * picks. `scripts/draft-mock.ts` is the CLI over this module.
 */

/** A row of the persisted draft board, as `draft:board` serves it and the fixture stores it. */
export interface MockBoardRow {
  playerId: string;
  name: string;
  position: string;
  team: string | null;
  modelPoints: number | null;
  marketPoints: number | null;
  blendedPoints: number;
  adp: number | null;
  adpStdev: number | null;
  byeWeek: number | null;
  availability: number;
  p10: number;
  p90: number;
  quantileProvenance: "measured" | "placeholder";
}

/** The frozen board fixture: provenance alongside the rows, so a reader can check both. */
export interface BoardFixture {
  source: string;
  season: number;
  scoringId: string;
  teams: number;
  /** `publishedAt` of the board run the rows came from, epoch milliseconds. */
  computedAt: number;
  rows: MockBoardRow[];
}

export interface MockDraftSetup {
  teams: number;
  /** Our 1-based draft slot. */
  slot: number;
  rounds: number;
  config: LeagueConfig;
  seed: number;
  candidateLimit: number;
}

export interface MockPick {
  /** 1-based overall pick number. */
  overall: number;
  round: number;
  /** The pick as a manager reads it: `2.06`. */
  label: string;
  teamIndex: number;
  seat: number;
  mine: boolean;
  playerId: string;
  /**
   * The panel as it stood when this pick was made — leader first, ordered exactly as
   * displayed. Only our own picks carry one; opponents never see a panel.
   */
  recommendations: ChampionshipRecommendation[] | null;
}

export interface MockDraftReplay {
  setup: MockDraftSetup;
  picks: MockPick[];
}

/** Formats an overall pick the way a draft room says it: round dot slot-in-round. */
export function pickLabelFor(overall: number, teams: number): string {
  const round = Math.ceil(overall / teams);
  const inRound = overall - (round - 1) * teams;
  return `${round}.${String(inRound).padStart(2, "0")}`;
}

/**
 * The frozen fixture's rows with byes resolved the way `runBuildDraftBoard` now resolves
 * them: the team's schedule bye first, the row's own (market-fed) bye as the fallback.
 *
 * This is the harness's `--schedule-byes` mode. The fixture is the audit's frozen record
 * and is never regenerated — its `computedAt` and row count are pinned by tests — so the
 * ingest fix's effect is measured by applying the same pure derivation to the frozen rows
 * at load time and replaying. On this board the derivation only ever *fills*: every
 * market-published bye agrees with the schedule (measured: 213 rows agree, 0 disagree,
 * 388 teamed rows fill from null), so a row changes exactly when its bye was null and its
 * team has a schedule bye. Teamless rows pass through untouched and keep null — those are
 * the residue the simulation's assumed-bye charge exists for.
 */
export function applyTeamByes(
  rows: readonly MockBoardRow[],
  byes: ReadonlyMap<string, number>,
): MockBoardRow[] {
  return rows.map((row) => {
    if (row.team === null) return row;
    const bye = byes.get(row.team);
    if (bye === undefined || bye === row.byeWeek) return row;
    return { ...row, byeWeek: bye };
  });
}

/** The board row → `PlayerRisk` conversion the draft page performs, verbatim. */
export function toPlayerRisk(row: MockBoardRow): PlayerRisk {
  return {
    id: row.playerId,
    name: row.name,
    position: row.position,
    weeklyMean: perGameRate(row.blendedPoints, row.availability),
    p10: row.p10,
    p90: row.p90,
    byeWeek: row.byeWeek,
    availability: row.availability,
    adp: row.adp,
    adpStdev: row.adpStdev,
  };
}

function fail(message: string): never {
  throw new Error(message);
}

/** The positions a board row may carry — the NFL fantasy set the season sim slots. */
const VALID_POSITIONS = new Set(["QB", "RB", "WR", "TE", "K", "DST"]);

function expectNumberOrNull(value: unknown, where: string): number | null {
  if (value === null) return null;
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return fail(`${where} must be a finite number or null, got ${JSON.stringify(value)}`);
}

function expectNumber(value: unknown, where: string): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return fail(`${where} must be a finite number, got ${JSON.stringify(value)}`);
}

function expectString(value: unknown, where: string): string {
  if (typeof value === "string" && value.length > 0) return value;
  return fail(`${where} must be a non-empty string, got ${JSON.stringify(value)}`);
}

/**
 * Validates a parsed fixture into a typed board.
 *
 * Field by field rather than a cast, because #37's harness died exactly this way: an
 * untyped fixture supplied a field that did not exist, every score silently became zero,
 * and the numbers looked plausible. #64 requires the invalid shape to fail loudly instead
 * of producing output, and this is where it does.
 */
export function parseBoardFixture(value: unknown): BoardFixture {
  if (typeof value !== "object" || value === null) fail("fixture must be an object");
  const fixture = value as Record<string, unknown>;
  const rowsRaw = fixture.rows;
  if (!Array.isArray(rowsRaw) || rowsRaw.length === 0) {
    fail("fixture.rows must be a non-empty array");
  }
  const rows = rowsRaw.map((raw, index): MockBoardRow => {
    if (typeof raw !== "object" || raw === null) fail(`rows[${index}] must be an object`);
    const row = raw as Record<string, unknown>;
    const where = (field: string) => `rows[${index}].${field}`;
    const team = row.team;
    if (team !== null && typeof team !== "string") {
      fail(`${where("team")} must be a string or null`);
    }
    const provenance = row.quantileProvenance;
    if (provenance !== "measured" && provenance !== "placeholder") {
      fail(`${where("quantileProvenance")} must be "measured" or "placeholder"`);
    }
    const parsed: MockBoardRow = {
      playerId: expectString(row.playerId, where("playerId")),
      name: expectString(row.name, where("name")),
      position: expectString(row.position, where("position")),
      team,
      modelPoints: expectNumberOrNull(row.modelPoints, where("modelPoints")),
      marketPoints: expectNumberOrNull(row.marketPoints, where("marketPoints")),
      blendedPoints: expectNumber(row.blendedPoints, where("blendedPoints")),
      adp: expectNumberOrNull(row.adp, where("adp")),
      adpStdev: expectNumberOrNull(row.adpStdev, where("adpStdev")),
      byeWeek: expectNumberOrNull(row.byeWeek, where("byeWeek")),
      availability: expectNumber(row.availability, where("availability")),
      p10: expectNumber(row.p10, where("p10")),
      p90: expectNumber(row.p90, where("p90")),
      quantileProvenance: provenance,
    };
    // Domain gates, past shape: a finite number in the wrong range distorts every
    // championship figure as silently as #37's missing field did. A misspelt position
    // fills no roster slot; an availability outside (0, 1] is hidden downstream by
    // `perGameRate`'s clamp rather than surfaced; quantiles out of order invert the
    // outcome distribution; an ADP of zero or less cannot come from `parseAdp`, which
    // drops such rows at the source.
    if (!VALID_POSITIONS.has(parsed.position)) {
      fail(`${where("position")} must be one of QB/RB/WR/TE/K/DST, got "${parsed.position}"`);
    }
    if (parsed.availability <= 0 || parsed.availability > 1) {
      fail(`${where("availability")} must be within (0, 1], got ${parsed.availability}`);
    }
    if (parsed.p10 > parsed.p90) {
      fail(`${where("p10")} must not exceed p90, got ${parsed.p10} > ${parsed.p90}`);
    }
    if (parsed.adp !== null && parsed.adp <= 0) {
      fail(`${where("adp")} must be positive or null, got ${parsed.adp}`);
    }
    if (
      parsed.byeWeek !== null &&
      (!Number.isInteger(parsed.byeWeek) || parsed.byeWeek < 1 || parsed.byeWeek > 18)
    ) {
      fail(`${where("byeWeek")} must be a week within 1..18 or null, got ${parsed.byeWeek}`);
    }
    return parsed;
  });
  // Board order is rank order — the checks and the replay both read a row's index as its
  // overall rank, so a fixture whose rows have been reordered is a different board.
  for (let i = 1; i < rows.length; i += 1) {
    const previous = rows[i - 1];
    const current = rows[i];
    const ordered =
      previous.blendedPoints > current.blendedPoints ||
      (previous.blendedPoints === current.blendedPoints &&
        // `<`, though a mutation run reports `<=` as a survivor: equal ids only occur for
        // a duplicated row, and the id-uniqueness check below rejects that on its own.
        previous.playerId < current.playerId);
    if (!ordered) {
      fail(
        `rows[${i}] is out of board order: ${previous.name} (${previous.blendedPoints}) ` +
          `before ${current.name} (${current.blendedPoints})`,
      );
    }
  }
  const ids = new Set(rows.map((row) => row.playerId));
  if (ids.size !== rows.length) fail("fixture rows contain a duplicate playerId");
  return {
    source: expectString(fixture.source, "source"),
    season: expectNumber(fixture.season, "season"),
    scoringId: expectString(fixture.scoringId, "scoringId"),
    teams: expectNumber(fixture.teams, "teams"),
    computedAt: expectNumber(fixture.computedAt, "computedAt"),
    rows,
  };
}

/**
 * The state the page would hand the worker with `picksSoFar` recorded and `overall` on
 * the clock.
 *
 * Exported and tested directly, because "the replay mirrors the page" is this module's
 * central claim and a claim buried in a loop cannot be asserted: team 0 is our seat
 * whatever the slot, rosters are rebuilt from the recorded picks in pick order, and
 * `remainingPicks` is filtered from the current pick *inclusive* — on our turn its first
 * entry is the pick being made, which is what tells the policy the candidate occupies
 * this pick and not a later one.
 */
export function stateAtPick(
  board: readonly MockBoardRow[],
  picksSoFar: ReadonlyArray<{ overall: number; playerId: string }>,
  league: { teams: number; slot: number; rounds: number },
  overall: number,
): DraftPolicyState {
  const { teams, slot, rounds } = league;
  const pool = board.map(toPlayerRisk);
  const byId = new Map(pool.map((player) => [player.id, player]));
  const owners = pickOwnership(teams, slot, rounds);
  const rosters: PlayerRisk[][] = Array.from({ length: teams }, () => []);
  const taken = new Set<string>();
  for (const made of picksSoFar) {
    const team = owners.get(made.overall);
    const player = byId.get(made.playerId);
    if (team === undefined || player === undefined) continue;
    rosters[team].push(player);
    taken.add(player.id);
  }
  const draftTeams: DraftTeam[] = rosters.map((roster, index) => ({
    id: `t${index}`,
    name: index === 0 ? "You" : `Seat ${seatForTeamIndex(index, slot)}`,
    roster,
    remainingPicks: [...owners.entries()]
      .filter(([pick, team]) => team === index && pick >= overall)
      .map(([pick]) => pick)
      // Kept verbatim from the page even though `pickOwnership` already yields each
      // team's picks ascending — which is why a mutation run reports the comparator as
      // a survivor. Dropping it here would quietly diverge from the page's construction
      // the day that iteration order changes.
      .sort((a, b) => a - b),
  }));
  return {
    teams: draftTeams,
    myTeamIndex: 0,
    available: pool.filter((player) => !taken.has(player.id)),
    rosterSize: rounds,
  };
}

/**
 * Plays the whole draft out, pick by pick, and returns every pick with the panel that
 * chose it.
 *
 * Deterministic: the engine is seeded, the opponents are a sort, and there is no clock
 * and no randomness anywhere in the loop. Two calls with the same board and setup return
 * identical replays, which is what lets a later PR show its fix as a delta against this
 * one's scoreboard.
 */
export function replayAdpMockDraft(
  board: readonly MockBoardRow[],
  setup: MockDraftSetup,
): MockDraftReplay {
  const { teams, slot, rounds, config, seed, candidateLimit } = setup;
  if (!Number.isInteger(teams) || teams < 2) fail(`teams must be at least 2, got ${teams}`);
  if (!Number.isInteger(slot) || slot < 1 || slot > teams) {
    fail(`slot must be within 1..${teams}, got ${slot}`);
  }
  if (!Number.isInteger(rounds) || rounds < 1) fail(`rounds must be positive, got ${rounds}`);
  const totalPicks = teams * rounds;
  if (board.length < totalPicks) {
    fail(`board has ${board.length} players but the draft needs ${totalPicks}`);
  }

  const pool = board.map(toPlayerRisk);
  const byId = new Map(pool.map((player) => [player.id, player]));
  const owners = pickOwnership(teams, slot, rounds);
  const taken = new Set<string>();
  // The worker's own capacity. A mutation run reports the number as a survivor, which is
  // correct and fine: the memo affects speed, never answers, so no test should pin it.
  const store = new LruMemoStore(256);
  const picks: MockPick[] = [];

  for (let overall = 1; overall <= totalPicks; overall += 1) {
    const teamIndex =
      owners.get(overall) ?? fail(`pick ${overall} has no owner — pickOwnership is broken`);
    let playerId: string;
    let recommendations: ChampionshipRecommendation[] | null = null;

    if (teamIndex === 0) {
      const state = stateAtPick(board, picks, { teams, slot, rounds }, overall);
      const result = recommendMemoized(store, state, config, seed, candidateLimit);
      const leader = result.recommendations[0];
      if (leader === undefined) {
        fail(`the panel returned no recommendation at pick ${overall}`);
      }
      playerId = leader.player.id;
      recommendations = result.recommendations;
    } else {
      // Strict market discipline: the lowest ADP still available, ties to the better
      // board rank — the pool's ADP sort with the top row taken. Unranked players sort
      // behind every ranked one, so an opponent only reaches them when the market's whole
      // list is gone. `?? Infinity`, never `||`: an ADP of zero is the market's first
      // pick, not a missing rank, and the falsy-zero collapse is a hazard this codebase
      // has shipped before.
      let best: PlayerRisk | null = null;
      let bestAdp = Number.POSITIVE_INFINITY;
      for (const player of pool) {
        if (taken.has(player.id)) continue;
        const adp = player.adp ?? Number.POSITIVE_INFINITY;
        if (best === null || adp < bestAdp) {
          best = player;
          bestAdp = adp;
        }
      }
      if (best === null) fail(`no player left for pick ${overall}`);
      playerId = best.id;
    }

    if (!byId.has(playerId)) fail(`picked player ${playerId} is not on the board`);
    taken.add(playerId);
    picks.push({
      overall,
      round: Math.ceil(overall / teams),
      label: pickLabelFor(overall, teams),
      teamIndex,
      seat: seatForTeamIndex(teamIndex, slot),
      mine: teamIndex === 0,
      playerId,
      recommendations,
    });
  }

  return { setup, picks };
}

// ---------------------------------------------------------------------------------------
// Property checks. Each pins one audit finding; `expected` records what the engine is
// measured to do today, and the PR that fixes the finding flips it. #91 is the ledger.
// ---------------------------------------------------------------------------------------

export type CheckId = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i";

/**
 * Rounds counted as "early" for the market-discipline check (a).
 *
 * The audited window, and since PR 3 also the gate's: `MARKET_GATE_ROUNDS` in
 * `lib/core/draft-policy.ts` holds a market-absent player off the shortlist through
 * exactly these rounds, and `mock.test.ts` pins the two constants to each other — a gate
 * narrower than the check would leave (a) asserting rounds nothing enforces.
 */
export const EARLY_ROUNDS = 6;

/** How many closing rounds a second kicker or defence is allowed to occupy (b). */
export const STREAMABLE_CLOSING_ROUNDS = 2;

/** Rounds ahead of its market round the first K/D-ST may reasonably go (d). */
export const MARKET_ROUND_TOLERANCE = 2;

/** The fewest wide receivers a half-PPR 2-FLEX roster can defend (e). */
export const MIN_WIDE_RECEIVERS = 4;

/** Smallest whole-round bound that accepts both corrected replays (five frozen, six scheduled). */
export const SKILL_MARKET_LEAD_ROUNDS = 6;

/**
 * Which board the replay ran on: the frozen fixture verbatim, or the fixture with byes
 * resolved from the schedule (`applyTeamByes`) — the measurement mode #91's PR 2 added.
 */
export type ReplayMode = "frozen" | "schedule-byes";

export interface CheckDefinition {
  id: CheckId;
  title: string;
  /**
   * The status the current engine earns on the frozen fixture. A `"fail"` here is a
   * documented defect with an open PR slot in #91, not a tolerance.
   */
  expected: "pass" | "fail";
  /**
   * The status the current engine earns in `--schedule-byes` mode — the same frozen
   * board with the ingest fix's bye derivation applied at load. Locked separately
   * because the two modes are two measurements: a fix PR flips whichever of the two its
   * change moves, in the same commit, and a divergence between them is itself evidence
   * (it isolates how much of a finding was the missing-bye subsidy).
   */
  expectedWithScheduleByes: "pass" | "fail";
  /** What the #88/#89 audit observed — the numbers this check exists to pin. */
  audit: string;
}

/** The expectation the exit contract enforces for a given replay mode. */
export function expectationFor(
  definition: CheckDefinition,
  mode: ReplayMode,
): "pass" | "fail" {
  return mode === "frozen" ? definition.expected : definition.expectedWithScheduleByes;
}

export const CHECK_DEFINITIONS: readonly CheckDefinition[] = [
  {
    id: "a",
    title: `no player absent from the market's list leads a pick in rounds 1-${EARLY_ROUNDS}`,
    // The check with the most instructive history on file, every step a measurement.
    // PR 2 alone (charging null byes) removed every market-absent early leader; PR 4
    // alone (ranking by title odds) did too — Gainwell's 2.06 lead needed the
    // missing-bye subsidy and the tie reorder together, and on the merged engine 2.06
    // takes Barkley, the very runner-up the audit displayed under him. But each PR's
    // all-clear was its own re-rolled ordering: merged, Colby Parkinson — no ADP, a
    // real model value — led 6.06 in BOTH modes, the audit's other (a) violation
    // reproduced verbatim. Which is the point the early flips missed: a market-absent
    // player whose model value is genuinely early-round-sized leads on model price
    // alone, and no amount of noise reduction fixes that.
    //
    // Flipped by PR 3's market-discipline gate — a structural exclusion, not another
    // re-rolled ordering: `applyMarketGate` (`lib/core/draft-policy.ts`) keeps a player
    // the board prices at `adp: null` off the recommendation shortlist through round
    // `MARKET_GATE_ROUNDS`, which a test pins equal to this check's `EARLY_ROUNDS`, so
    // inside the audited window the panel cannot offer a market-absent leader at all.
    // Measured on the merged engine in both modes: no market-absent leader at any pick
    // in rounds 1-6, Parkinson gone from 6.06, and 2.06 still goes to Barkley.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit:
      "Kenneth Gainwell (no ADP) led 2.06 at 14.5%±1.4 over Saquon Barkley's 16.2%±1.5; " +
      "Colby Parkinson (no ADP, a TE) led 6.06",
  },
  {
    id: "b",
    title:
      `at most one K and one D/ST before the final ` +
      `${STREAMABLE_CLOSING_ROUNDS} rounds`,
    // Flipped by PR 5's streamable-position discipline, and structurally rather than by
    // an ordering: `applyStreamableDiscipline` (`lib/core/draft-policy.ts`) keeps a
    // second kicker or defence off the recommendation shortlist until the closing
    // rounds, and `mock.test.ts` pins the policy's own closing-round count to this
    // check's `STREAMABLE_CLOSING_ROUNDS`.
    //
    // Stated at the strength the code supports, which is the shortlist and one
    // exception: like the market gate, the discipline stands down rather than return an
    // empty panel, so a state whose *every* candidate is a withheld kicker or defence
    // would still be offered one. On this board — 622 rows, of which 35 are streamable —
    // that cannot fire, and it did not: the replay took one of each in both modes.
    //
    // The depth model was changed underneath it in the same PR, and what that buys is
    // agreement rather than enforcement: `coverValue` now takes a waiver-wire share, and
    // at a share of one — kicker and defence, argued in `lib/nfl/roster.ts` — a
    // reserve's cover term is scaled to nothing, so the base policy and the rollouts,
    // which are deliberately ungated, stop *wanting* a second one instead of being
    // stopped from taking one. The cap is what makes "at most one" true of the advice;
    // the pricing is what stops the cap being a rule the rest of the engine argues with.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "second kicker at 12.06 behind Dicker at 9.05; defences at 5.05 and 16.06",
  },
  {
    id: "c",
    title:
      "no same-position pick on consecutive own turns where the second outranks the first",
    // The check that keeps changing hands, and each hand is a measurement. PR 1: pass
    // (the audit's Goff-then-Nix pair was browser click timing, not the deterministic
    // panel). PR 4, ranking by title odds: FAIL on its engine — the honest ranking
    // re-rolls sampling noise every turn where the old hidden key had masked churn with
    // a stable order, and nothing charges the engine for buying a position it just
    // filled (#89.A); #91 hands the flip-back to PR 5. Measured on the merged engine,
    // the two modes split: the frozen board (403 null byes, each an assumed-week draw)
    // churns and fails; resolve the byes from the schedule and the churn disappears —
    // the honest ranking plus bye noise crosses the churn threshold, the honest ranking
    // alone on clean byes does not. PR 2 also contributes a recorded near-miss of the
    // same shape: an interim draft drew the assumed bye across the playoff bracket and
    // that noise alone churned the frozen board.
    //
    // PR 3's market gate flipped the frozen column back to pass, and the honest reading
    // is the modest one: the gate reshapes the early picks (Pitts at 6.06 where
    // Parkinson led), and on the reshuffled sequence the frozen board's bye-noise churn
    // does not recross the threshold. That is a measurement of this ordering, not a fix
    // for (c)'s mechanism — nothing yet charges the engine for buying a position it
    // just filled (#89.A), which PR 5 still owns. What PR 5 inherits is a regression
    // lock in both columns rather than a flip-back: if its cost model re-rolls this
    // ordering and the churn returns, this expectation rings and the flip is documented
    // there, per the same contract this comment is obeying.
    //
    // PR 5 closed the mechanism rather than re-rolling past it, and the lock rang twice
    // on the way — which is the whole point of arming it. Its streamable discipline
    // reshuffled both replays and the churn came straight back: tight end at 9.05 then a
    // better tight end at 10.06 in the frozen mode, back at 2.06 then the better back at
    // 3.05 with the byes resolved. `applyOutbidDiscipline` is the charge #89.A said was
    // missing — past the starting slots a position dedicates, a candidate who outranks
    // somebody we already hold there is withheld, because he was on the board at the turn
    // we took the lesser one and nothing since is information about him. Both columns
    // pass on the merged engine with it, and neither passes without it.
    //
    // The audit string below is only the browser run's observation; the replay never
    // reproduced the Goff-then-Nix pair (click timing, measured, per #91).
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit:
      "the browser run took Goff 10.06 then Nix 11.05 — Nix starts, the round-10 pick " +
      "benched",
  },
  {
    id: "d",
    // "No more than N rounds before", not "within N rounds": the check is one-sided on
    // purpose — taking a kicker *later* than his market round is discipline, not a
    // defect, and PR 5's fix will push K/D-ST later than market for good.
    title:
      `first K and first D/ST no more than ${MARKET_ROUND_TOLERANCE} rounds ` +
      `before their market round`,
    // Flipped by PR 5, structurally, and by the stricter of the two available rules: the
    // policy's `STREAMABLE_MARKET_LEAD_ROUNDS` is zero, so a kicker or defence is not
    // offered before his *own* market round, while this check tolerates
    // `MARKET_ROUND_TOLERANCE` rounds of lead. `mock.test.ts` pins the policy at or below
    // the tolerance — an inequality, not the equality (a) carries, because a policy
    // stricter than its check still enforces it. The same one exception applies as to
    // (b): the discipline yields rather than empty the panel, which no board this size
    // can produce and this one did not.
    //
    // The argument for zero is the one `docs/draft-validation.md` already makes about
    // these two positions and no others: the model does not project them, their entire
    // price is the market's, and their weekly spread is still a placeholder. An engine
    // taking one six rounds early is overruling the only price it has, on no signal of
    // its own. Measured on the merged engine: the defence went 16.06 and 14.06 in the two
    // modes against a market round of 13 and 14, the kicker 14.06 and 15.05 against 14
    // and 15 — late, which this check deliberately does not penalise.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "Seattle D/ST at 5.05 against a round-9 market (ADP 82.9); first K at 9.05 " +
      "against a round-15 market (ADP 143)",
  },
  {
    id: "e",
    title: `at least ${MIN_WIDE_RECEIVERS} wide receivers on the final roster`,
    // PR 5 left this failing because the prefilter gave a full hypothetical replacement
    // to an empty slot even where `wireCover` was zero. Flipped by replacement consistency:
    // both the starting and absence terms now credit only the covered share, so WR holes
    // match the objective's zero and both replays draft four receivers. Kept as the
    // narrower historical lock; (g) is the general property.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "two WRs in sixteen rounds of a half-PPR 2-FLEX league, with 165 still available",
  },
  {
    id: "f",
    title: "the displayed leader's championship odds are not below any runner-up's",
    // Flipped by PR 4: the panel now descends by title odds throughout — the paired
    // vs-leader comparison is the ranking instrument and the tie flag is a label, not a
    // sort key — so the top card carries the panel's highest number by construction,
    // whatever the board's byes say. Measured before the fix: inverted at 11 of 16
    // picks on this fixture.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "leader shown at 14.5% with the #2 row at 16.2% — the tie reorder by playoff " +
      "probability promoted the lower title number",
  },
  {
    id: "g",
    title: "the completed roster can field a legal starting lineup in every season week",
    // #88 finding 3 was about an unusable roster, not a receiver count in isolation.
    // In every configured week, remove players on bye and run the same exact matching the
    // objective uses. A hypothetical waiver body is available only where the existing wire
    // share is positive; zero-cover positions must be filled by the drafted roster.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit:
      "the replay finished with four QBs in frozen mode and six TEs with schedule byes, " +
      "while its starting lineup could not be covered through every bye week",
  },
  {
    id: "h",
    title: `no market-priced skill player is taken more than ${SKILL_MARKET_LEAD_ROUNDS} rounds before his market round`,
    // Before league-aware QB cover, schedule-byes took Caleb Williams seven rounds early.
    // Six is measured, not chosen: it is the smallest bound both corrected modes pass.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "the frozen replay took Stafford six rounds early; schedule-byes took Caleb Williams seven rounds early",
  },
  {
    id: "i",
    title: "no position exceeds its startable slots plus its measured reserve allowance",
    // One reserve per dedicated modeled starter, plus one shared reserve for a position
    // eligible at FLEX. Schedule-byes measures the latter: seven RBs against four starts.
    // Market-only K/D-ST get no reserve. Three QBs exceed one start plus one reserve.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit: "all prior seven checks passed while both replay modes carried three QBs in a 1-QB league",
  },
];

export interface CheckOutcome extends CheckDefinition {
  status: "pass" | "fail";
  /** One line per observed violation; empty when the check passes. */
  violations: string[];
}

/** Percentage with one decimal, as the panel prints it. */
function pct(probability: number): string {
  return `${(probability * 100).toFixed(1)}%`;
}

/**
 * Runs every property check against a finished replay.
 *
 * Reads the replay and the board alone — no engine, no fixture file — so a test can hand
 * it a constructed pick log and probe each check's boundary without paying for a
 * simulation.
 */
export function evaluateChecks(
  replay: MockDraftReplay,
  board: readonly MockBoardRow[],
): CheckOutcome[] {
  const { teams, rounds } = replay.setup;
  const totalPicks = teams * rounds;
  const rowById = new Map(board.map((row) => [row.playerId, row]));
  const rankById = new Map(board.map((row, index) => [row.playerId, index + 1]));
  // `??` here and on the rank lookups below reads `||` in a mutation report as a
  // survivor: a hit is always a row object or a rank of at least one, never falsy, so
  // the two operators genuinely cannot disagree on these lookups.
  const rowFor = (playerId: string): MockBoardRow =>
    rowById.get(playerId) ?? fail(`replay picked ${playerId}, which is not on the board`);
  const mine = replay.picks.filter((pick) => pick.mine);
  const violations: Record<CheckId, string[]> = {
    a: [], b: [], c: [], d: [], e: [], f: [], g: [], h: [], i: [],
  };

  // (a) A row the market has not ranked must not lead an early-round panel. The leader is
  // checked rather than the pick taken, because the finding is about what the panel says —
  // the audit happened to take every leader, but a leader ignored is still a claim made.
  for (const pick of mine) {
    if (pick.round > EARLY_ROUNDS || pick.recommendations === null) continue;
    const leader = pick.recommendations[0];
    if (leader !== undefined && leader.player.adp == null) {
      const row = rowFor(leader.player.id);
      violations.a.push(
        `${pick.label} leader ${row.name} (${row.position}${
          row.team === null ? "" : `, ${row.team}`
        }) has no market rank`,
      );
    }
  }

  // (b) Streamable positions before the closing rounds. The closing rounds are exempt
  // because a last-round second defence costs nothing better.
  const closingStart = rounds - STREAMABLE_CLOSING_ROUNDS + 1;
  for (const position of ["K", "DST"]) {
    const early = mine.filter(
      (pick) => pick.round < closingStart && rowFor(pick.playerId).position === position,
    );
    if (early.length > 1) {
      violations.b.push(
        `${early.length} ${position === "DST" ? "D/ST" : position} before round ` +
          `${closingStart}: ${early
            .map((pick) => `${rowFor(pick.playerId).name} at ${pick.label}`)
            .join(", ")}`,
      );
    }
  }

  // (c) Consecutive own turns spending on the same position, with the second pick the
  // better player by the board's own ranking — the engine outbidding itself.
  for (let i = 1; i < mine.length; i += 1) {
    const first = rowFor(mine[i - 1].playerId);
    const second = rowFor(mine[i].playerId);
    if (first.position !== second.position) continue;
    const firstRank = rankById.get(first.playerId) ?? fail(`${first.playerId} unranked`);
    const secondRank = rankById.get(second.playerId) ?? fail(`${second.playerId} unranked`);
    // `<`, with `<=` surviving mutation: equal ranks would need the same player at both
    // picks, and a replay's taken-set makes a repeated pick impossible.
    if (secondRank < firstRank) {
      violations.c.push(
        `${first.position} ${first.name} at ${mine[i - 1].label} (board #${firstRank}) then ` +
          `${second.name} at ${mine[i].label} (board #${secondRank}) — the second pick ` +
          `benches the first`,
      );
    }
  }

  // (d) The first kicker and the first defence, against where the market drafts them. An
  // unranked pick is priced where the survival model prices every unranked player: behind
  // the whole draft.
  for (const position of ["K", "DST"]) {
    const first = mine.find((pick) => rowFor(pick.playerId).position === position);
    if (first === undefined) continue;
    const row = rowFor(first.playerId);
    const marketPick = row.adp ?? totalPicks + UNRANKED_ADP_PADDING;
    const marketRound = Math.ceil(marketPick / teams);
    if (first.round < marketRound - MARKET_ROUND_TOLERANCE) {
      violations.d.push(
        `first ${position === "DST" ? "D/ST" : position} ${row.name} at ${first.label}, ` +
          `${marketRound - first.round} rounds ahead of its round-${marketRound} market ` +
          `(ADP ${row.adp === null ? "none" : row.adp.toFixed(1)})`,
      );
    }
  }

  // (e) Wide receivers on the final roster.
  const wideReceivers = mine.filter((pick) => rowFor(pick.playerId).position === "WR");
  if (wideReceivers.length < MIN_WIDE_RECEIVERS) {
    violations.e.push(
      `${wideReceivers.length} WR drafted in ${rounds} rounds` +
        (wideReceivers.length > 0
          ? ` (${wideReceivers
              .map((pick) => `${rowFor(pick.playerId).name} at ${pick.label}`)
              .join(", ")})`
          : ""),
    );
  }

  // (f) The leader label must not sit on a lower championship number than a row below it.
  // Within-tie reordering may be defensible; displaying it as "best available" is the
  // finding, and this measures exactly the displayed ordering.
  for (const pick of mine) {
    // The length guard is convenience, not correctness — destructuring an empty panel
    // yields no leader and no runners-up and the loop below does nothing, which is why a
    // mutation run reports the zero as a survivor.
    if (pick.recommendations === null || pick.recommendations.length === 0) continue;
    const [leader, ...rest] = pick.recommendations;
    for (const other of rest) {
      if (other.championshipProbability > leader.championshipProbability) {
        violations.f.push(
          `${pick.label} leader ${leader.player.name} at ${pct(
            leader.championshipProbability,
          )} sits above ${other.player.name} at ${pct(other.championshipProbability)}`,
        );
        break;
      }
    }
  }

  // (g) Unit points make this an eligibility question only. A positive eligible player
  // always beats the solver's empty dummy column, independent of projections or ordering.
  const seasonWeeks = [
    ...new Set([...replay.setup.config.weeks, ...replay.setup.config.playoffWeeks]),
    // `a - b` → `a + b` survives equivalently: every week is checked independently and
    // the final status depends only on whether any violation exists, never their order.
  ].sort((a, b) => a - b);
  const finalRoster = mine.map((pick) => rowFor(pick.playerId));
  const wirePlayers = [...replay.setup.config.wireCover.entries()].flatMap(
    ([position, share]) => {
      // Match replacementLevels: malformed coverage cannot create a waiver player that the
      // valuation baseline itself refuses to count, and finite coverage stays in [0, 1].
      const normalized = Number.isFinite(share) ? Math.max(0, Math.min(1, share)) : 0;
      return normalized > 0
        ? replay.setup.config.slots
            .filter((slot) => slot.eligiblePositions.includes(position))
            .map((_, index) => ({
              id: `__wire__${position}__${index}`,
              name: `waiver ${position}`,
              position,
              projectedPoints: Number.EPSILON,
              availability: "active" as const,
            }))
        : [];
    },
  );
  for (const week of seasonWeeks) {
    const lineup = solveLineup(replay.setup.config.slots, [
      ...finalRoster.map((player) => ({
        id: player.playerId,
        name: player.name,
        position: player.position,
        projectedPoints: Number.EPSILON,
        availability: player.byeWeek === week ? "bye" as const : "active" as const,
      })),
      ...wirePlayers,
    ]);
    const empty = lineup.assignments.filter((assignment) => assignment.competitorId === null);
    if (empty.length > 0) {
      violations.g.push(
        `week ${week}: cannot fill ${empty.map((assignment) => assignment.slotLabel).join(", ")}`,
      );
    }
  }

  // (h) Unpriced rows are owned by check (a)'s explicit window, not assigned a fake round.
  const skillPositions = new Set(["QB", "RB", "WR", "TE"]);
  for (const pick of mine) {
    const row = rowFor(pick.playerId);
    if (!skillPositions.has(row.position) || row.adp === null) continue;
    const marketRound = Math.ceil(row.adp / teams);
    const lead = marketRound - pick.round;
    if (lead > SKILL_MARKET_LEAD_ROUNDS) {
      violations.h.push(
        `${row.position} ${row.name} at ${pick.label}, ${lead} rounds ahead of its ` +
          `round-${marketRound} market (ADP ${row.adp.toFixed(1)})`,
      );
    }
  }

  // (i) FLEX creates one shared reserve allowance, not one per flexible slot.
  const rosterCounts = new Map<string, number>();
  for (const player of finalRoster) {
    // `?? 0` and `|| 0` are equivalent here: counts are positive once present, and the
    // only falsy numeric value is the fallback itself.
    rosterCounts.set(player.position, (rosterCounts.get(player.position) ?? 0) + 1);
  }
  for (const [position, count] of rosterCounts) {
    const startable = replay.setup.config.slots.filter((slot) =>
      slot.eligiblePositions.includes(position)).length;
    const dedicated = replay.setup.config.slots.filter((slot) =>
      slot.eligiblePositions.length === 1 && slot.eligiblePositions[0] === position).length;
    const flexReserve = replay.setup.config.slots.some((slot) =>
      slot.eligiblePositions.length > 1 && slot.eligiblePositions.includes(position)) ? 1 : 0;
    const reserve = replay.setup.config.unprojectedPositions.has(position)
      ? 0
      : dedicated + flexReserve;
    const limit = startable + reserve;
    if (count > limit) {
      violations.i.push(
        `${count} ${position === "DST" ? "D/ST" : position} drafted; ${startable} ` +
          `startable slot${startable === 1 ? "" : "s"} + ${reserve} reserve allowance permits ${limit}`,
      );
    }
  }

  return CHECK_DEFINITIONS.map((definition) => ({
    ...definition,
    status: violations[definition.id].length === 0 ? "pass" : "fail",
    violations: violations[definition.id],
  }));
}

/**
 * The outcomes that disagree with their documented expectation for the given mode.
 *
 * This is the harness's alarm — an unexpected pass means a fix landed without flipping
 * its check, an unexpected failure is a regression — and the alarm's logic lives here
 * rather than in the script so a test can ring it. The script's only job is to print it
 * and set the exit code. Both replay modes carry the same contract; they differ only in
 * which expectation column is enforced.
 */
export function unexpectedOutcomes(
  outcomes: readonly CheckOutcome[],
  mode: ReplayMode = "frozen",
): CheckOutcome[] {
  return outcomes.filter((outcome) => outcome.status !== expectationFor(outcome, mode));
}

/**
 * Why a fixture cannot stand in for the league the harness claims to replay, or `null`
 * when it can.
 *
 * A sentence rather than a boolean, because the refusal is user-facing: the harness
 * would rather say which board it was handed than mislabel another board's results as
 * the audit's.
 */
export function fixtureLeagueMismatch(
  fixture: BoardFixture,
  league: { season: number; scoringId: string; teams: number },
): string | null {
  if (
    fixture.season === league.season &&
    fixture.scoringId === league.scoringId &&
    fixture.teams === league.teams
  ) {
    return null;
  }
  return (
    `fixture is for season ${fixture.season}, ${fixture.scoringId}, ` +
    `${fixture.teams} teams; this harness replays the ${league.season} ` +
    `${league.scoringId} ${league.teams}-team audit and refuses to mislabel ` +
    `another board's results`
  );
}
