import { pickOwnership, seatForTeamIndex, UNRANKED_ADP_PADDING } from "../../core/draft";
import { LruMemoStore, recommendMemoized } from "../../core/draft-memo";
import type {
  ChampionshipRecommendation,
  DraftPolicyState,
  DraftTeam,
} from "../../core/draft-policy";
import type { PlayerRisk } from "../../core/roster-utility";
import type { LeagueConfig } from "../../core/season-sim";
import { perGameRate } from "./value";

/**
 * A deterministic mock draft: nine opponents drafting strictly by market rank, our seat
 * taking the recommendation panel's #1 every turn.
 *
 * This is the harness behind the #88/#89 audit, codified. The audit was a browser run on
 * production — opponents took the top of the pool sorted by ADP, our seat took the leader
 * as presented, and the roster that fell out started three players the market had never
 * ranked, benched a kicker drafted in round 9 behind another drafted in round 12, and
 * finished a half-PPR 2-FLEX draft with two wide receivers. Every one of those is a
 * property this module asserts, as a **documented expectation per check** in
 * `CHECK_DEFINITIONS` that the PR fixing a finding flips in the same commit. No fix ships
 * without flipping its check; no check flips without a fix. See #91 for the sequence,
 * #64 for why the harness is policy-level.
 *
 * Since PR 2 (byes from the schedule) the harness replays in two modes, each with its own
 * expectation column: the frozen fixture verbatim, and `--schedule-byes` — the same rows
 * with byes resolved from the schedule the way ingest now resolves them
 * (`applyTeamByes`). The pair brackets the bye fix: the frozen mode measures the engine on
 * the audit's data (403 null byes, now each charged as an assumed absent week), the
 * schedule-byes mode measures it on the data a rebuilt board carries. Measured flips so
 * far: (a) passes in both modes — charging the null byes alone removed the subsidy that
 * led Gainwell to 2.06, and the panel takes Barkley, the audit's displayed runner-up —
 * and (c) split, failing frozen and passing with schedule byes; the definitions below
 * record both mechanisms.
 *
 * ## Where the replay and the audit's transcript agree, and where they cannot
 *
 * On the frozen board, the engine as PR 1 shipped it reproduced the audit's picks
 * 1.05 through 5.05 exactly — including the 2.06 capture verbatim: Gainwell leading at
 * 14.5%±1.4 with Barkley displayed at 16.2%±1.5. The fixture's `computedAt` is the build
 * #88 cites (07:01 US Eastern, which #88 rounds to "07:00"), and reproducing the
 * *displayed percentages* was strong evidence the board matches — a different board would
 * move them. Later PRs change these picks deliberately (PR 2 already has: charging the
 * null byes moves 2.06 to Barkley) — the scoreboard is the contract, not the pick list,
 * and the audit-parity claim belongs to PR 1's commit, `b27faf6`. One discrepancy is on
 * record rather than resolved: #89.E reports Kyle Pitts absent from the market's list,
 * while this board carries him at ADP 81.7 with a bye; both cannot be literally true of
 * the same build, and the reproduced figures argue the board is right and #89.E's
 * raw-list check missed him.
 *
 * From 6.06 on the two runs diverge: the live panel recomputes after every recorded
 * pick, the audit's automation clicked whatever was *presented*, and #88 records the
 * reply gate preventing three stale takes — clicks on a player already drafted, which is
 * only possible if the presented panel lagged the recorded picks. A stale panel whose
 * leader was still available blocks nothing, and a replay cannot and should not
 * reproduce click timing: #91 defines the harness as "same board → same draft", which is
 * this function, not the browser session. The findings still open after PR 2 reproduce
 * here through their own mechanisms — both modes still draft a second kicker well before
 * the closing rounds, take the first kicker at least three rounds ahead of its market,
 * finish with two wide receivers, and invert the leader label against a runner-up's
 * displayed odds.
 *
 * ## Why the opponents are strict-ADP
 *
 * #64 rules out grading the policy against opponents generated by the policy itself —
 * that is circular. The market's consensus draft order is the one opponent model whose
 * provenance is independent of this codebase, and "the pool sorted by ADP, top row taken"
 * is exactly what the audit's automation clicked. Players the market has not ranked sort
 * behind every player it has (`adp: null` → after every number), mirroring the pool's
 * ADP sort on `/draft`.
 *
 * ## Why the replay mirrors the page rather than calling the policy directly
 *
 * Our picks go through `recommendMemoized` — the same entry point
 * `recommend.worker.ts` uses, canonicalization included — with the page's own seed and
 * state construction (`app/(app)/draft/page.tsx`): rosters keyed off the pick-ownership
 * map with team 0 as our seat, `remainingPicks` filtered from the current pick, the pool
 * in board order. A harness that rebuilt the state its own way would measure its own
 * reconstruction, not the product; this one reproduces the audit's picks on the audit's
 * board build, which is what makes its failures evidence rather than anecdote.
 *
 * Pure by construction: the board arrives as data (the frozen fixture under
 * `tests/fixtures/`), the engine is seeded, and the same inputs replay the same 160
 * picks. `scripts/draft-mock.ts` is the CLI over this module.
 */

/** A row of the persisted draft board, as `draft:board` serves it and the fixture stores it. */
export interface MockBoardRow {
  playerId: string;
  name: string;
  position: string;
  team: string | null;
  modelPoints: number | null;
  marketPoints: number | null;
  blendedPoints: number;
  adp: number | null;
  adpStdev: number | null;
  byeWeek: number | null;
  availability: number;
  p10: number;
  p90: number;
  quantileProvenance: "measured" | "placeholder";
}

/** The frozen board fixture: provenance alongside the rows, so a reader can check both. */
export interface BoardFixture {
  source: string;
  season: number;
  scoringId: string;
  teams: number;
  /** `publishedAt` of the board run the rows came from, epoch milliseconds. */
  computedAt: number;
  rows: MockBoardRow[];
}

export interface MockDraftSetup {
  teams: number;
  /** Our 1-based draft slot. */
  slot: number;
  rounds: number;
  config: LeagueConfig;
  seed: number;
  candidateLimit: number;
}

export interface MockPick {
  /** 1-based overall pick number. */
  overall: number;
  round: number;
  /** The pick as a manager reads it: `2.06`. */
  label: string;
  teamIndex: number;
  seat: number;
  mine: boolean;
  playerId: string;
  /**
   * The panel as it stood when this pick was made — leader first, ordered exactly as
   * displayed. Only our own picks carry one; opponents never see a panel.
   */
  recommendations: ChampionshipRecommendation[] | null;
}

export interface MockDraftReplay {
  setup: MockDraftSetup;
  picks: MockPick[];
}

/** Formats an overall pick the way a draft room says it: round dot slot-in-round. */
export function pickLabelFor(overall: number, teams: number): string {
  const round = Math.ceil(overall / teams);
  const inRound = overall - (round - 1) * teams;
  return `${round}.${String(inRound).padStart(2, "0")}`;
}

/**
 * The frozen fixture's rows with byes resolved the way `runBuildDraftBoard` now resolves
 * them: the team's schedule bye first, the row's own (market-fed) bye as the fallback.
 *
 * This is the harness's `--schedule-byes` mode. The fixture is the audit's frozen record
 * and is never regenerated — its `computedAt` and row count are pinned by tests — so the
 * ingest fix's effect is measured by applying the same pure derivation to the frozen rows
 * at load time and replaying. On this board the derivation only ever *fills*: every
 * market-published bye agrees with the schedule (measured: 213 rows agree, 0 disagree,
 * 388 teamed rows fill from null), so a row changes exactly when its bye was null and its
 * team has a schedule bye. Teamless rows pass through untouched and keep null — those are
 * the residue the simulation's assumed-bye charge exists for.
 */
export function applyTeamByes(
  rows: readonly MockBoardRow[],
  byes: ReadonlyMap<string, number>,
): MockBoardRow[] {
  return rows.map((row) => {
    if (row.team === null) return row;
    const bye = byes.get(row.team);
    if (bye === undefined || bye === row.byeWeek) return row;
    return { ...row, byeWeek: bye };
  });
}

/** The board row → `PlayerRisk` conversion the draft page performs, verbatim. */
export function toPlayerRisk(row: MockBoardRow): PlayerRisk {
  return {
    id: row.playerId,
    name: row.name,
    position: row.position,
    weeklyMean: perGameRate(row.blendedPoints, row.availability),
    p10: row.p10,
    p90: row.p90,
    byeWeek: row.byeWeek,
    availability: row.availability,
    adp: row.adp,
    adpStdev: row.adpStdev,
  };
}

function fail(message: string): never {
  throw new Error(message);
}

/** The positions a board row may carry — the NFL fantasy set the season sim slots. */
const VALID_POSITIONS = new Set(["QB", "RB", "WR", "TE", "K", "DST"]);

function expectNumberOrNull(value: unknown, where: string): number | null {
  if (value === null) return null;
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return fail(`${where} must be a finite number or null, got ${JSON.stringify(value)}`);
}

function expectNumber(value: unknown, where: string): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return fail(`${where} must be a finite number, got ${JSON.stringify(value)}`);
}

function expectString(value: unknown, where: string): string {
  if (typeof value === "string" && value.length > 0) return value;
  return fail(`${where} must be a non-empty string, got ${JSON.stringify(value)}`);
}

/**
 * Validates a parsed fixture into a typed board.
 *
 * Field by field rather than a cast, because #37's harness died exactly this way: an
 * untyped fixture supplied a field that did not exist, every score silently became zero,
 * and the numbers looked plausible. #64 requires the invalid shape to fail loudly instead
 * of producing output, and this is where it does.
 */
export function parseBoardFixture(value: unknown): BoardFixture {
  if (typeof value !== "object" || value === null) fail("fixture must be an object");
  const fixture = value as Record<string, unknown>;
  const rowsRaw = fixture.rows;
  if (!Array.isArray(rowsRaw) || rowsRaw.length === 0) {
    fail("fixture.rows must be a non-empty array");
  }
  const rows = rowsRaw.map((raw, index): MockBoardRow => {
    if (typeof raw !== "object" || raw === null) fail(`rows[${index}] must be an object`);
    const row = raw as Record<string, unknown>;
    const where = (field: string) => `rows[${index}].${field}`;
    const team = row.team;
    if (team !== null && typeof team !== "string") {
      fail(`${where("team")} must be a string or null`);
    }
    const provenance = row.quantileProvenance;
    if (provenance !== "measured" && provenance !== "placeholder") {
      fail(`${where("quantileProvenance")} must be "measured" or "placeholder"`);
    }
    const parsed: MockBoardRow = {
      playerId: expectString(row.playerId, where("playerId")),
      name: expectString(row.name, where("name")),
      position: expectString(row.position, where("position")),
      team,
      modelPoints: expectNumberOrNull(row.modelPoints, where("modelPoints")),
      marketPoints: expectNumberOrNull(row.marketPoints, where("marketPoints")),
      blendedPoints: expectNumber(row.blendedPoints, where("blendedPoints")),
      adp: expectNumberOrNull(row.adp, where("adp")),
      adpStdev: expectNumberOrNull(row.adpStdev, where("adpStdev")),
      byeWeek: expectNumberOrNull(row.byeWeek, where("byeWeek")),
      availability: expectNumber(row.availability, where("availability")),
      p10: expectNumber(row.p10, where("p10")),
      p90: expectNumber(row.p90, where("p90")),
      quantileProvenance: provenance,
    };
    // Domain gates, past shape: a finite number in the wrong range distorts every
    // championship figure as silently as #37's missing field did. A misspelt position
    // fills no roster slot; an availability outside (0, 1] is hidden downstream by
    // `perGameRate`'s clamp rather than surfaced; quantiles out of order invert the
    // outcome distribution; an ADP of zero or less cannot come from `parseAdp`, which
    // drops such rows at the source.
    if (!VALID_POSITIONS.has(parsed.position)) {
      fail(`${where("position")} must be one of QB/RB/WR/TE/K/DST, got "${parsed.position}"`);
    }
    if (parsed.availability <= 0 || parsed.availability > 1) {
      fail(`${where("availability")} must be within (0, 1], got ${parsed.availability}`);
    }
    if (parsed.p10 > parsed.p90) {
      fail(`${where("p10")} must not exceed p90, got ${parsed.p10} > ${parsed.p90}`);
    }
    if (parsed.adp !== null && parsed.adp <= 0) {
      fail(`${where("adp")} must be positive or null, got ${parsed.adp}`);
    }
    if (
      parsed.byeWeek !== null &&
      (!Number.isInteger(parsed.byeWeek) || parsed.byeWeek < 1 || parsed.byeWeek > 18)
    ) {
      fail(`${where("byeWeek")} must be a week within 1..18 or null, got ${parsed.byeWeek}`);
    }
    return parsed;
  });
  // Board order is rank order — the checks and the replay both read a row's index as its
  // overall rank, so a fixture whose rows have been reordered is a different board.
  for (let i = 1; i < rows.length; i += 1) {
    const previous = rows[i - 1];
    const current = rows[i];
    const ordered =
      previous.blendedPoints > current.blendedPoints ||
      (previous.blendedPoints === current.blendedPoints &&
        // `<`, though a mutation run reports `<=` as a survivor: equal ids only occur for
        // a duplicated row, and the id-uniqueness check below rejects that on its own.
        previous.playerId < current.playerId);
    if (!ordered) {
      fail(
        `rows[${i}] is out of board order: ${previous.name} (${previous.blendedPoints}) ` +
          `before ${current.name} (${current.blendedPoints})`,
      );
    }
  }
  const ids = new Set(rows.map((row) => row.playerId));
  if (ids.size !== rows.length) fail("fixture rows contain a duplicate playerId");
  return {
    source: expectString(fixture.source, "source"),
    season: expectNumber(fixture.season, "season"),
    scoringId: expectString(fixture.scoringId, "scoringId"),
    teams: expectNumber(fixture.teams, "teams"),
    computedAt: expectNumber(fixture.computedAt, "computedAt"),
    rows,
  };
}

/**
 * The state the page would hand the worker with `picksSoFar` recorded and `overall` on
 * the clock.
 *
 * Exported and tested directly, because "the replay mirrors the page" is this module's
 * central claim and a claim buried in a loop cannot be asserted: team 0 is our seat
 * whatever the slot, rosters are rebuilt from the recorded picks in pick order, and
 * `remainingPicks` is filtered from the current pick *inclusive* — on our turn its first
 * entry is the pick being made, which is what tells the policy the candidate occupies
 * this pick and not a later one.
 */
export function stateAtPick(
  board: readonly MockBoardRow[],
  picksSoFar: ReadonlyArray<{ overall: number; playerId: string }>,
  league: { teams: number; slot: number; rounds: number },
  overall: number,
): DraftPolicyState {
  const { teams, slot, rounds } = league;
  const pool = board.map(toPlayerRisk);
  const byId = new Map(pool.map((player) => [player.id, player]));
  const owners = pickOwnership(teams, slot, rounds);
  const rosters: PlayerRisk[][] = Array.from({ length: teams }, () => []);
  const taken = new Set<string>();
  for (const made of picksSoFar) {
    const team = owners.get(made.overall);
    const player = byId.get(made.playerId);
    if (team === undefined || player === undefined) continue;
    rosters[team].push(player);
    taken.add(player.id);
  }
  const draftTeams: DraftTeam[] = rosters.map((roster, index) => ({
    id: `t${index}`,
    name: index === 0 ? "You" : `Seat ${seatForTeamIndex(index, slot)}`,
    roster,
    remainingPicks: [...owners.entries()]
      .filter(([pick, team]) => team === index && pick >= overall)
      .map(([pick]) => pick)
      // Kept verbatim from the page even though `pickOwnership` already yields each
      // team's picks ascending — which is why a mutation run reports the comparator as
      // a survivor. Dropping it here would quietly diverge from the page's construction
      // the day that iteration order changes.
      .sort((a, b) => a - b),
  }));
  return {
    teams: draftTeams,
    myTeamIndex: 0,
    available: pool.filter((player) => !taken.has(player.id)),
    rosterSize: rounds,
  };
}

/**
 * Plays the whole draft out, pick by pick, and returns every pick with the panel that
 * chose it.
 *
 * Deterministic: the engine is seeded, the opponents are a sort, and there is no clock
 * and no randomness anywhere in the loop. Two calls with the same board and setup return
 * identical replays, which is what lets a later PR show its fix as a delta against this
 * one's scoreboard.
 */
export function replayAdpMockDraft(
  board: readonly MockBoardRow[],
  setup: MockDraftSetup,
): MockDraftReplay {
  const { teams, slot, rounds, config, seed, candidateLimit } = setup;
  if (!Number.isInteger(teams) || teams < 2) fail(`teams must be at least 2, got ${teams}`);
  if (!Number.isInteger(slot) || slot < 1 || slot > teams) {
    fail(`slot must be within 1..${teams}, got ${slot}`);
  }
  if (!Number.isInteger(rounds) || rounds < 1) fail(`rounds must be positive, got ${rounds}`);
  const totalPicks = teams * rounds;
  if (board.length < totalPicks) {
    fail(`board has ${board.length} players but the draft needs ${totalPicks}`);
  }

  const pool = board.map(toPlayerRisk);
  const byId = new Map(pool.map((player) => [player.id, player]));
  const owners = pickOwnership(teams, slot, rounds);
  const taken = new Set<string>();
  // The worker's own capacity. A mutation run reports the number as a survivor, which is
  // correct and fine: the memo affects speed, never answers, so no test should pin it.
  const store = new LruMemoStore(256);
  const picks: MockPick[] = [];

  for (let overall = 1; overall <= totalPicks; overall += 1) {
    const teamIndex =
      owners.get(overall) ?? fail(`pick ${overall} has no owner — pickOwnership is broken`);
    let playerId: string;
    let recommendations: ChampionshipRecommendation[] | null = null;

    if (teamIndex === 0) {
      const state = stateAtPick(board, picks, { teams, slot, rounds }, overall);
      const result = recommendMemoized(store, state, config, seed, candidateLimit);
      const leader = result.recommendations[0];
      if (leader === undefined) {
        fail(`the panel returned no recommendation at pick ${overall}`);
      }
      playerId = leader.player.id;
      recommendations = result.recommendations;
    } else {
      // Strict market discipline: the lowest ADP still available, ties to the better
      // board rank — the pool's ADP sort with the top row taken. Unranked players sort
      // behind every ranked one, so an opponent only reaches them when the market's whole
      // list is gone. `?? Infinity`, never `||`: an ADP of zero is the market's first
      // pick, not a missing rank, and the falsy-zero collapse is a hazard this codebase
      // has shipped before.
      let best: PlayerRisk | null = null;
      let bestAdp = Number.POSITIVE_INFINITY;
      for (const player of pool) {
        if (taken.has(player.id)) continue;
        const adp = player.adp ?? Number.POSITIVE_INFINITY;
        if (best === null || adp < bestAdp) {
          best = player;
          bestAdp = adp;
        }
      }
      if (best === null) fail(`no player left for pick ${overall}`);
      playerId = best.id;
    }

    if (!byId.has(playerId)) fail(`picked player ${playerId} is not on the board`);
    taken.add(playerId);
    picks.push({
      overall,
      round: Math.ceil(overall / teams),
      label: pickLabelFor(overall, teams),
      teamIndex,
      seat: seatForTeamIndex(teamIndex, slot),
      mine: teamIndex === 0,
      playerId,
      recommendations,
    });
  }

  return { setup, picks };
}

// ---------------------------------------------------------------------------------------
// Property checks. Each pins one audit finding; `expected` records what the engine is
// measured to do today, and the PR that fixes the finding flips it. #91 is the ledger.
// ---------------------------------------------------------------------------------------

export type CheckId = "a" | "b" | "c" | "d" | "e" | "f";

/** Rounds counted as "early" for the market-discipline check (a). */
export const EARLY_ROUNDS = 6;

/** How many closing rounds a second kicker or defence is allowed to occupy (b). */
export const STREAMABLE_CLOSING_ROUNDS = 2;

/** Rounds ahead of its market round the first K/D-ST may reasonably go (d). */
export const MARKET_ROUND_TOLERANCE = 2;

/** The fewest wide receivers a half-PPR 2-FLEX roster can defend (e). */
export const MIN_WIDE_RECEIVERS = 4;

/**
 * Which board the replay ran on: the frozen fixture verbatim, or the fixture with byes
 * resolved from the schedule (`applyTeamByes`) — the measurement mode #91's PR 2 added.
 */
export type ReplayMode = "frozen" | "schedule-byes";

export interface CheckDefinition {
  id: CheckId;
  title: string;
  /**
   * The status the current engine earns on the frozen fixture. A `"fail"` here is a
   * documented defect with an open PR slot in #91, not a tolerance.
   */
  expected: "pass" | "fail";
  /**
   * The status the current engine earns in `--schedule-byes` mode — the same frozen
   * board with the ingest fix's bye derivation applied at load. Locked separately
   * because the two modes are two measurements: a fix PR flips whichever of the two its
   * change moves, in the same commit, and a divergence between them is itself evidence
   * (it isolates how much of a finding was the missing-bye subsidy).
   */
  expectedWithScheduleByes: "pass" | "fail";
  /** What the #88/#89 audit observed — the numbers this check exists to pin. */
  audit: string;
}

/** The expectation the exit contract enforces for a given replay mode. */
export function expectationFor(
  definition: CheckDefinition,
  mode: ReplayMode,
): "pass" | "fail" {
  return mode === "frozen" ? definition.expected : definition.expectedWithScheduleByes;
}

export const CHECK_DEFINITIONS: readonly CheckDefinition[] = [
  {
    id: "a",
    title: `no player absent from the market's list leads a pick in rounds 1-${EARLY_ROUNDS}`,
    // Flipped by PR 2 (byes), not by the market gate #91 assigned it to. Measured on this
    // board: charging a null bye as an assumed absent week is by itself enough to stop
    // every market-absent row leading an early pick — 2.06 now takes Barkley, the very
    // runner-up the audit displayed under Gainwell. That is evidence the audit's (a)
    // violations *were* the missing-bye subsidy here, not proof they cannot recur: a
    // market-absent player whose model value is genuinely early-round-sized would still
    // lead, and PR 3's discipline gate remains the structural guarantee. Until it lands,
    // this check is the regression lock on the subsidy staying closed.
    expected: "pass",
    expectedWithScheduleByes: "pass",
    audit:
      "Kenneth Gainwell (no ADP) led 2.06 at 14.5%±1.4 over Saquon Barkley's 16.2%±1.5; " +
      "Colby Parkinson (no ADP, a TE) led 6.06",
  },
  {
    id: "b",
    title:
      `at most one K and one D/ST before the final ` +
      `${STREAMABLE_CLOSING_ROUNDS} rounds`,
    expected: "fail",
    expectedWithScheduleByes: "fail",
    audit: "second kicker at 12.06 behind Dicker at 9.05; defences at 5.05 and 16.06",
  },
  {
    id: "c",
    title:
      "no same-position pick on consecutive own turns where the second outranks the first",
    // The one check whose two columns disagree, and the disagreement is the measurement.
    // PR 1 measured this passing (the audit's Goff→Nix pair was click timing, not
    // policy). PR 2's sim change re-surfaced it on the *frozen* board: with 403 null
    // byes each charged as an assumed week, the tie ordering churns and 11.05 takes
    // Hunter Henry (board #120) with Colby Parkinson (#84) taken next — the engine
    // outbidding itself again. Resolve the byes from the schedule (`--schedule-byes`)
    // and the churn disappears, which isolates the residual as tie-noise on top of bye
    // noise. The frozen column stays "fail" until #91's PR 4 ranks ties by the paired
    // comparison; the schedule-byes column is the regression lock on today's pass.
    expected: "fail",
    expectedWithScheduleByes: "pass",
    audit:
      "the browser run took Goff 10.06 then Nix 11.05 (Nix starts, the round-10 pick " +
      "benched); the deterministic replay does not reproduce that pair — measured, per #91",
  },
  {
    id: "d",
    // "No more than N rounds before", not "within N rounds": the check is one-sided on
    // purpose — taking a kicker *later* than his market round is discipline, not a
    // defect, and PR 5's fix will push K/D-ST later than market for good.
    title:
      `first K and first D/ST no more than ${MARKET_ROUND_TOLERANCE} rounds ` +
      `before their market round`,
    expected: "fail",
    expectedWithScheduleByes: "fail",
    audit: "Seattle D/ST at 5.05 against a round-9 market (ADP 82.9); first K at 9.05 " +
      "against a round-15 market (ADP 143)",
  },
  {
    id: "e",
    title: `at least ${MIN_WIDE_RECEIVERS} wide receivers on the final roster`,
    expected: "fail",
    expectedWithScheduleByes: "fail",
    audit: "two WRs in sixteen rounds of a half-PPR 2-FLEX league, with 165 still available",
  },
  {
    id: "f",
    title: "the displayed leader's championship odds are not below any runner-up's",
    expected: "fail",
    expectedWithScheduleByes: "fail",
    audit: "leader shown at 14.5% with the #2 row at 16.2% — the tie reorder by playoff " +
      "probability promoted the lower title number",
  },
];

export interface CheckOutcome extends CheckDefinition {
  status: "pass" | "fail";
  /** One line per observed violation; empty when the check passes. */
  violations: string[];
}

/** Percentage with one decimal, as the panel prints it. */
function pct(probability: number): string {
  return `${(probability * 100).toFixed(1)}%`;
}

/**
 * Runs every property check against a finished replay.
 *
 * Reads the replay and the board alone — no engine, no fixture file — so a test can hand
 * it a constructed pick log and probe each check's boundary without paying for a
 * simulation.
 */
export function evaluateChecks(
  replay: MockDraftReplay,
  board: readonly MockBoardRow[],
): CheckOutcome[] {
  const { teams, rounds } = replay.setup;
  const totalPicks = teams * rounds;
  const rowById = new Map(board.map((row) => [row.playerId, row]));
  const rankById = new Map(board.map((row, index) => [row.playerId, index + 1]));
  // `??` here and on the rank lookups below reads `||` in a mutation report as a
  // survivor: a hit is always a row object or a rank of at least one, never falsy, so
  // the two operators genuinely cannot disagree on these lookups.
  const rowFor = (playerId: string): MockBoardRow =>
    rowById.get(playerId) ?? fail(`replay picked ${playerId}, which is not on the board`);
  const mine = replay.picks.filter((pick) => pick.mine);
  const violations: Record<CheckId, string[]> = { a: [], b: [], c: [], d: [], e: [], f: [] };

  // (a) A row the market has not ranked must not lead an early-round panel. The leader is
  // checked rather than the pick taken, because the finding is about what the panel says —
  // the audit happened to take every leader, but a leader ignored is still a claim made.
  for (const pick of mine) {
    if (pick.round > EARLY_ROUNDS || pick.recommendations === null) continue;
    const leader = pick.recommendations[0];
    if (leader !== undefined && leader.player.adp == null) {
      const row = rowFor(leader.player.id);
      violations.a.push(
        `${pick.label} leader ${row.name} (${row.position}${
          row.team === null ? "" : `, ${row.team}`
        }) has no market rank`,
      );
    }
  }

  // (b) Streamable positions before the closing rounds. The closing rounds are exempt
  // because a last-round second defence costs nothing better.
  const closingStart = rounds - STREAMABLE_CLOSING_ROUNDS + 1;
  for (const position of ["K", "DST"]) {
    const early = mine.filter(
      (pick) => pick.round < closingStart && rowFor(pick.playerId).position === position,
    );
    if (early.length > 1) {
      violations.b.push(
        `${early.length} ${position === "DST" ? "D/ST" : position} before round ` +
          `${closingStart}: ${early
            .map((pick) => `${rowFor(pick.playerId).name} at ${pick.label}`)
            .join(", ")}`,
      );
    }
  }

  // (c) Consecutive own turns spending on the same position, with the second pick the
  // better player by the board's own ranking — the engine outbidding itself.
  for (let i = 1; i < mine.length; i += 1) {
    const first = rowFor(mine[i - 1].playerId);
    const second = rowFor(mine[i].playerId);
    if (first.position !== second.position) continue;
    const firstRank = rankById.get(first.playerId) ?? fail(`${first.playerId} unranked`);
    const secondRank = rankById.get(second.playerId) ?? fail(`${second.playerId} unranked`);
    // `<`, with `<=` surviving mutation: equal ranks would need the same player at both
    // picks, and a replay's taken-set makes a repeated pick impossible.
    if (secondRank < firstRank) {
      violations.c.push(
        `${first.position} ${first.name} at ${mine[i - 1].label} (board #${firstRank}) then ` +
          `${second.name} at ${mine[i].label} (board #${secondRank}) — the second pick ` +
          `benches the first`,
      );
    }
  }

  // (d) The first kicker and the first defence, against where the market drafts them. An
  // unranked pick is priced where the survival model prices every unranked player: behind
  // the whole draft.
  for (const position of ["K", "DST"]) {
    const first = mine.find((pick) => rowFor(pick.playerId).position === position);
    if (first === undefined) continue;
    const row = rowFor(first.playerId);
    const marketPick = row.adp ?? totalPicks + UNRANKED_ADP_PADDING;
    const marketRound = Math.ceil(marketPick / teams);
    if (first.round < marketRound - MARKET_ROUND_TOLERANCE) {
      violations.d.push(
        `first ${position === "DST" ? "D/ST" : position} ${row.name} at ${first.label}, ` +
          `${marketRound - first.round} rounds ahead of its round-${marketRound} market ` +
          `(ADP ${row.adp === null ? "none" : row.adp.toFixed(1)})`,
      );
    }
  }

  // (e) Wide receivers on the final roster.
  const wideReceivers = mine.filter((pick) => rowFor(pick.playerId).position === "WR");
  if (wideReceivers.length < MIN_WIDE_RECEIVERS) {
    violations.e.push(
      `${wideReceivers.length} WR drafted in ${rounds} rounds` +
        (wideReceivers.length > 0
          ? ` (${wideReceivers
              .map((pick) => `${rowFor(pick.playerId).name} at ${pick.label}`)
              .join(", ")})`
          : ""),
    );
  }

  // (f) The leader label must not sit on a lower championship number than a row below it.
  // Within-tie reordering may be defensible; displaying it as "best available" is the
  // finding, and this measures exactly the displayed ordering.
  for (const pick of mine) {
    // The length guard is convenience, not correctness — destructuring an empty panel
    // yields no leader and no runners-up and the loop below does nothing, which is why a
    // mutation run reports the zero as a survivor.
    if (pick.recommendations === null || pick.recommendations.length === 0) continue;
    const [leader, ...rest] = pick.recommendations;
    for (const other of rest) {
      if (other.championshipProbability > leader.championshipProbability) {
        violations.f.push(
          `${pick.label} leader ${leader.player.name} at ${pct(
            leader.championshipProbability,
          )} sits above ${other.player.name} at ${pct(other.championshipProbability)}`,
        );
        break;
      }
    }
  }

  return CHECK_DEFINITIONS.map((definition) => ({
    ...definition,
    status: violations[definition.id].length === 0 ? "pass" : "fail",
    violations: violations[definition.id],
  }));
}

/**
 * The outcomes that disagree with their documented expectation for the given mode.
 *
 * This is the harness's alarm — an unexpected pass means a fix landed without flipping
 * its check, an unexpected failure is a regression — and the alarm's logic lives here
 * rather than in the script so a test can ring it. The script's only job is to print it
 * and set the exit code. Both replay modes carry the same contract; they differ only in
 * which expectation column is enforced.
 */
export function unexpectedOutcomes(
  outcomes: readonly CheckOutcome[],
  mode: ReplayMode = "frozen",
): CheckOutcome[] {
  return outcomes.filter((outcome) => outcome.status !== expectationFor(outcome, mode));
}

/**
 * Why a fixture cannot stand in for the league the harness claims to replay, or `null`
 * when it can.
 *
 * A sentence rather than a boolean, because the refusal is user-facing: the harness
 * would rather say which board it was handed than mislabel another board's results as
 * the audit's.
 */
export function fixtureLeagueMismatch(
  fixture: BoardFixture,
  league: { season: number; scoringId: string; teams: number },
): string | null {
  if (
    fixture.season === league.season &&
    fixture.scoringId === league.scoringId &&
    fixture.teams === league.teams
  ) {
    return null;
  }
  return (
    `fixture is for season ${fixture.season}, ${fixture.scoringId}, ` +
    `${fixture.teams} teams; this harness replays the ${league.season} ` +
    `${league.scoringId} ${league.teams}-team audit and refuses to mislabel ` +
    `another board's results`
  );
}
